# Generated by Django 6.0.4 on 2026-05-06 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('Id_Emp', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Embauche', models.DateField()),
                ('CIN', models.CharField(max_length=8, unique=True)),
                ('Debut_Shift', models.TimeField()),
                ('Fin_Shift', models.TimeField()),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('Mail_Adress', models.CharField(max_length=254, unique=True)),
                ('Refister_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('employe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.employe')),
                ('Specialite', models.CharField(max_length=250)),
            ],
            bases=('Users.employe',),
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('employe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='Users.employe')),
                ('Id_Secretaire', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('Users.employe',),
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Compte_Bancaire', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField()),
                ('mois', models.IntegerField()),
                ('annee', models.IntegerField()),
                ('Date_Salaire', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaires', to='Users.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Id_Patient', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
    ]
