# Generated by Django 6.0.4 on 2026-05-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Register_Date',
            new_name='Refister_Date',
        ),
    ]
