# Generated by Django 6.0.4 on 2026-05-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PassWord',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
