# Generated by Django 6.0.4 on 2026-05-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_register_date_user_refister_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Refister_Date',
            new_name='Register_Date',
        ),
    ]
