# Generated by Django 6.0.4 on 2026-05-16 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonance',
            fields=[
                ('Id_Ord', models.AutoField(primary_key=True, serialize=False, verbose_name='Numero')),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('Id_Devis', models.AutoField(primary_key=True, serialize=False)),
                ('Devis_Pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient', to='Users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Dossier_Pat',
            fields=[
                ('Id_Dossier', models.AutoField(primary_key=True, serialize=False)),
                ('Patient_Cons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Lettre_Ref',
            fields=[
                ('Id_Lettre', models.AutoField(primary_key=True, serialize=False)),
                ('Recepteur', models.TextField()),
                ('Contenu', models.TextField()),
                ('Concerne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Objet_Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=300)),
                ('Qte', models.IntegerField()),
                ('PU', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ap_Devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Objets', to='RDV.devis')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('QTE', models.IntegerField(default=1)),
                ('Consommation', models.TextField(blank=True, null=True)),
                ('Ap_Ordonance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medicaments', to='RDV.ordonance')),
            ],
        ),
        migrations.CreateModel(
            name='Rendez_Vous',
            fields=[
                ('Id_RDV', models.AutoField(primary_key=True, serialize=False)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Moment', models.DateTimeField()),
                ('duree', models.IntegerField(default=30, help_text='Durée en minutes')),
                ('Status', models.CharField(choices=[('P', 'Prévu'), ('C', 'Confirmé'), ('A', 'Annulé'), ('T', 'Terminé')], default='P', max_length=1)),
                ('Current_Doc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.medecin', verbose_name='Medecin')),
                ('Current_Pat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.patient', verbose_name='Patient')),
            ],
            options={
                'ordering': ['Moment'],
            },
        ),
        migrations.AddField(
            model_name='ordonance',
            name='Rdv_concerne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RDV.rendez_vous', verbose_name='Rendez Vous'),
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('Id_Facture', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('P', 'payé'), ('N', 'non payé')], default='N', max_length=1)),
                ('Date_Payement', models.DateTimeField()),
                ('rdv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RDV.rendez_vous', verbose_name='Rendez Vous')),
            ],
        ),
        migrations.AddField(
            model_name='devis',
            name='Rdv_Cons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Devis', to='RDV.rendez_vous'),
        ),
        migrations.AddConstraint(
            model_name='rendez_vous',
            constraint=models.UniqueConstraint(fields=('Current_Doc', 'Moment'), name='unique_doctor_schedule'),
        ),
    ]
