# Generated by Django 6.0.4 on 2026-05-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendez_vous',
            name='Motif',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
