# Generated by Django 6.0.4 on 2026-05-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0002_rendez_vous_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendez_vous',
            name='Rappel_SMS',
            field=models.BooleanField(default=False),
        ),
    ]
