# Generated by Django 6.0.4 on 2026-05-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0003_rendez_vous_rappel_sms'),
        ('Users', '0003_rename_refister_date_user_register_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendez_vous',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='rendez_vous',
            name='unique_doctor_schedule',
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='Debut_Consultation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='Fin_Consultation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='Current_Doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdvs', to='Users.medecin'),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='Current_Pat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdvs', to='Users.patient'),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='Motif',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='Notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rendez_vous',
            name='duree',
            field=models.IntegerField(default=30, help_text='Durée réelle en minutes'),
        ),
    ]
