# Generated by Django 6.0.4 on 2026-05-18 17:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RDV', '0004_alter_rendez_vous_options_and_more'),
        ('Users', '0003_rename_refister_date_user_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='Date_Creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lettre_ref',
            name='Rdv_Cons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RDV.rendez_vous'),
        ),
        migrations.CreateModel(
            name='Certificat_Med',
            fields=[
                ('Id_Certif', models.AutoField(primary_key=True, serialize=False)),
                ('Contenu', models.TextField()),
                ('Date_Creation', models.DateTimeField(auto_now_add=True)),
                ('Patient_Cons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Users.patient')),
                ('Rdv_Cons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RDV.rendez_vous')),
            ],
        ),
    ]
